### ISSUE TITLE
Installing GMT.jl in Windows 10

### ISSUE THREAD

**Issue by dervisgursoy** [GenericMappingTools/GMT.jl#328] opened 2020-01-04 23:20 UTC
Dear all,

I am trying to use GMT to plot my GPS points (and make lines between them, etc). I downloaded and installed GMT version 6.0.0_win64. I am using julia 1.3.0 via jupyter notebook. 

I am trying to run the following code on Jupyter notebook:
![image](https://user-images.githubusercontent.com/59431310/71772752-40225800-2f16-11ea-8ec1-dd128cb7c0d2.png)

However, getting this error:

error compiling common_plot_xyz: error compiling gmt: could not load library “gmt_w64”
The specified module could not be found.

Any help appreciated. 
Thank you

**Comment by joa-quim** [comment] 2020-01-04 23:28
Ah, from ``jupyter``. For a long time I don't test it (will do).

What happens if you run the same command from REPL?

**Comment by dervisgursoy** [comment] 2020-01-04 23:41
It gives me this error in julia REPL:
![image](https://user-images.githubusercontent.com/59431310/71772909-6269a500-2f19-11ea-80f3-89dae3691d9d.png)

**Comment by joa-quim** [comment] 2020-01-04 23:49
OK, so it's working. The message says that you had one GMT5 installed before and now you are running GMT6. Please do as the warning message says otherwise it will still think you are using GMT5, which has a much more restrictive use.

Regarding the error. It's ``lc=:blue`` or ``lc="blue"`. Not ``lc=blue`` because ``blue`` is an unknown variable.

**Comment by joa-quim** [comment] 2020-01-05 01:22
And the ``gmt_w64`` error you are getting it because you didn't do what the warning message told you to do.

**Comment by dervisgursoy** [comment] 2020-01-05 01:38
@joa-quim thank you very much for your help.

Do you know what error message exactly saying? Since I didnt have "deps" folder under "src" folder that error messages wants me to do, I create a folder called "deps" in the following directory: 
"C:\---\.julia\packages\GMT\nfsRH\src\deps" 
After that, I placed GMT.jl file into "deps" folder. However, right now, I am getting this error at jupyter notebook:
![image](https://user-images.githubusercontent.com/59431310/71773814-b2e8fe80-2f29-11ea-8ce4-2180e5a4363d.png)

Any idea?

**Comment by joa-quim** [comment] 2020-01-05 01:47
Ah, ghrrr, my fault. It shouldn't have any ``deps`` and absolutely do not move the ``GMT.jl`` file. Just edit the ``src\GMT.jl`` (adding a space somewhere, save the file, remove the space and save again should do it). Sorry for this clumsy solution but don't know how to force recompile otherwise.

**Comment by dervisgursoy** [comment] 2020-01-05 02:14
No worries. 
I copy and paste GMT.jl file to another folder, put the space and delete it again. I restart the jupyuter notebook but I am having still the following error:

![image](https://user-images.githubusercontent.com/59431310/71774133-cf3b6a00-2f2e-11ea-9d5d-8efd91487b10.png)

Thank you

**Comment by joa-quim** [comment] 2020-01-05 02:21
> I copy and paste GMT.jl file to another folder

I hope that means you put it back to original location. Put a space and remove it is not enough. You must save the file in between that operation. The idea is to make julia think that the ``GMT.jl`` was changed and hence force recompile. An alternative is to delete the contents of  ``....\.julia\compiled\v1.3\GMT``

**Comment by dervisgursoy** [comment] 2020-01-05 03:11
@joa-quim Thank you that solved the problem, GMT.jl is now working. 

I am also interested in finding driving distance (not the euclidean distance) between two GPS points. Is that possible in GMT.jl? If so, is there any solid example showing this?
Thank you

**Comment by joa-quim** [comment] 2020-01-05 03:17
Good. 
If you mean finding the distance along a line, yes. But you need to know that line (that can have many vertices). The program that you'll use is ``mapproject``. See its docs in GMT (not GMT.jl, which does not have yet more than the on-line help)

We can continue this tomorrow, now is very late in here and I go to bed.

**Comment by joa-quim** [comment] 2020-01-05 03:18
Ah, and adding a line in Discourse post saying that the problem is solved and was caused by a GMT versions issue, would be nice.

**Comment by dervisgursoy** [comment] 2020-01-06 23:21
Dear all,

I would like to plot the GPS points (latitude and longitude) on satellite map similar to this:

![image](https://user-images.githubusercontent.com/59431310/71856133-98895f00-30a8-11ea-8d29-1ff9db6cb7a3.png)

It is best if I use GMT.jl, or any Julia packages to do that because I am using Julia for whole of my other analyses. 
Any help would be appreciated.

**Comment by joa-quim** [comment] 2020-01-06 23:38
Could you please post this in the [GMT forum](https://forum.generic-mapping-tools.org) instead? Other than not being related to this issue, there are more people that can help there. I'm the only Julia user here but as long as GMT can do it, GMT.jl has to be able to do it too. Otherwise there is a bug.

**Comment by joa-quim** [comment] 2020-01-07 00:09
Closing this issue as solved

**Closed by joa-quim** 2020-01-07 00:09 UTC
