### ISSUE TITLE
Trouble plotting png or jpg files after updating to gmt 6.1

### ISSUE THREAD

**Issue by thisdudeiscalledsomeone** [GenericMappingTools/GMT.jl#389] opened 2020-07-07 05:27 UTC
Hello,

I though that i would be smart and downloaded GMT 6.1.0 and updated GMT.jl through julia. 
However, i since can't output any files in jpg or png (the only output that works is in postscript). 

For example, if we use the example available at https://www.generic-mapping-tools.org/GMT.jl/latest/examples/

`topo = makecpt(color=:rainbow, range=(1000,5000,500), continuous=true);
grdimage("@tut_relief.nc", shade=(azimuth=100, norm="e0.8"), proj=:Mercator, frame=:a, color=topo)
colorbar!(pos=(anchor=:TC,length=(12.5,0.6), horizontal=true, offset=(0,1.0)),
          color=topo, frame=(ylabel=:m,), fmt=:jpg, show=true)`

I get the following error :

ERROR: LoadError: get_image: programming error, output matrix is empty
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] get_image(::Ptr{Nothing}, ::Ptr{Nothing}) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\gmt_main.jl:475
 [3] GMTJL_Get_Object(::Ptr{Nothing}, ::GMT.GMT_RESOURCE) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\gmt_main.jl:824
 [4] gmt(::String) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\gmt_main.jl:256
 [5] showfig(::Dict{Symbol,Any}, ::String, ::String, ::String, ::Bool, ::String) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:2478
 [6] finish_PS_module(::Dict{Symbol,Any}, ::String, ::String, ::Bool, ::Bool, ::Bool, ::GMT.GMTcpt, ::Vararg{Any,N} where N) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:2578
 [7] colorbar(::String, ::Nothing; first::Bool, kwargs::Base.Iterators.Pairs{Symbol,Any,NTuple{5,Symbol},NamedTuple{(:pos, :color, :frame, :fmt, :show),Tuple{NamedTuple{(:anchor, :length, :horizontal, :offset),Tuple{Symbol,Tuple{Float64,Float64},Bool,Tuple{Int64,Float64}}},GMT.GMTcpt,NamedTuple{(:ylabel,),Tuple{Symbol}},Symbol,Bool}}}) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\psscale.jl:85
 [8] #colorbar!#243 at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\psscale.jl:93 [inlined]
 [9] top-level scope at H:\juliatest\test.jl:7
 [10] include(::Module, ::String) at .\Base.jl:377
 [11] exec_options(::Base.JLOptions) at .\client.jl:288
 [12] _start() at .\client.jl:484
in expression starting at H:\juliatest\test.jl:7

But removing the fmt=:jpg, returns the correct map in postscript.

I tried to do some troubleshooting with test GMT through Julia, it returns the following errors :

(@v1.4) pkg> test GMT
    Testing GMT
Status `C:\Users\uusseerr\AppData\Local\Temp\jl_f4mvP0\Manifest.toml`
  [5752ebe1] GMT v0.21.0
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [b77e0a4c] InteractiveUtils
  [56ddb016] Logging
  [d6f4376e] Markdown
  [de0858da] Printf
  [9a3f8284] Random
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [8dfed614] Test
  [4ec0a83e] Unicode
6.1.0
┌ Warning: Unknown units request (lolo) Ignoring it
└ @ GMT C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:1783
┌ Warning: Color lines (or fill) from a color scale was selected but no color scale provided. Expect ...
└ @ GMT C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\psxy.jl:117
┌ Warning: Ignoring the axis 'equal' request because figsize with Width and Height already provided.
└ @ GMT C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:256
┌ Warning: Very likely the projection name (blabla) is unknown to me. Expect troubles
└ @ GMT C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:379
┌ Warning: Empty units. Ignoring this units request.
└ @ GMT C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:1762
gmt gmtset [core] 6.1.0 [64-bit] [MP] - Change individual GMT default settings

usage: gmt gmtset [-C | -D[s|u] | -G<defaultsfile>] [-[BJRXYp]<value>] PARAMETER1 value1 PARAMETER2 value2 PARAMETER3 value3 ...

        For available PARAMETERS, see gmt.conf man page.

        FITCIRCLE
        GMT2KML & KML2GMT
ERROR: LoadError: Failed to destroy object used in the interface bewteen GMT and Julia
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] gmt(::String, ::Array{GMT.GMTdataset,1}, ::Vararg{Any,N} where N) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\gmt_main.jl:270
 [3] common_grd(::Dict{Symbol,Any}, ::String, ::Array{GMT.GMTdataset,1}, ::Nothing) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\common_options.jl:2419
 [4] gmt2kml(::String, ::Array{GMT.GMTdataset,1}; kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:F, :W),Tuple{Symbol,Tuple{Int64,Symbol}}}}) at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\gmt2kml.jl:110
 [5] #gmt2kml#59 at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\src\gmt2kml.jl:114 [inlined]
 [6] top-level scope at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\test\runtests.jl:256
 [7] include(::String) at .\client.jl:439
 [8] top-level scope at none:6
in expression starting at C:\Users\uusseerr\.julia\packages\GMT\CRQUT\test\runtests.jl:12
ERROR: Package GMT errored during testing

I also tried several times some fresh install by removing GMT.jl and reinstalling GMT 6.0.0, however this one doesn't work either, and with GMT6.1.0, which always result in the empty matrix error.
I verified that once uninstalled there were no previous version still available somewhere on the computer, and made sure that the windows PATH is set to C:\programs\gmt6\bin.

**Comment by htyeim** [comment] 2020-07-07 08:50
The same problem with GMT 6.1.  Updating GMT.jl (`] add GMT#master`) could solve some problems. Maybe it is necessary to publish a new version in Register.

**Comment by joa-quim** [comment] 2020-07-07 09:18
Thanks, it looks I (or GMT) screw up somewhere with the file names and none of the tests cached it

```
julia> topo = makecpt(color=:rainbow, range=(1000,5000,500), continuous=true); grdimage("@tut_relief.nc", shade=(azimuth=100, norm="e0.8"), proj=:Mercator, frame=:a, color=topo); colorbar!(pos=(anchor=:TC,length=(12.5,0.6), horizontal=true, offset=(0,1.0)), color=topo, frame=(ylabel=:m,), fmt=:jpg, show=true)
ERROR 4: `C:c:/j/.gmt/cache/\TMP\GMTjl_tmp.jpg' does not exist in the file system, and is not recognized as a supported dataset name.
```
This ``C:c:/j/.gmt/cache/\TMP\GMTjl_tmp.jpg'`` is very strange. It should have been ``C:\TMP\GMTjl_tmp.jpg``.

Regarding the other errors, yes GMT made recent changes that were taken care in GMT.jl but only in master. Will register a new version but before I need to find what's going on with the jpg screwed example.

**Comment by joa-quim** [comment] 2020-07-07 10:15
Shit. The problem is deeper in GMT
```
julia> gmt("psconvert -A1p -Qg4 -Qt4 C:\\TMP\\GMTjl_tmp.ps -Tj")
ERROR 4: `C:c:/j/.gmt/cache/\TMP\GMTjl_tmp.jpg' does not exist in the file system, and is not recognized as a supported dataset name.
psconvert [ERROR]: Unable to open C:\TMP\GMTjl_tmp.jpg.
```

**Comment by joa-quim** [comment] 2020-07-07 11:16
OK, found a way to workaround the problem, which will need to be fixed in GMT itself.
Master should work now. 
Will proceed to register a new version.

**Comment by thisdudeiscalledsomeone** [comment] 2020-07-07 17:27
I downloaded the master version of GMT.jl and i confirm that everything is back to normal !

**Comment by joa-quim** [comment] 2020-07-07 17:32
Good. Version 0.22 is also registered now so you can do a ``] update``

**Closed by joa-quim** 2020-07-07 17:32 UTC
